name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        django: ['3.2', '4.0', '4.1']
        wagtail: ['4.1', '4.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Tests
        run: |
          python -m pip install --upgrade pip tox
      - name: Test with tox
        run: |
            tox
        env:
            TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}
